#version: "3.8" #  specify docker-compose version  

services:  
  backend_test:
    build: ./flask
    container_name: flask_api_app_test
    ports:
      - "5000:5000"                 # expose the port to the host machine
    depends_on:
      db_test:                           # wait for the db_test service to be ready
        condition: service_healthy  # wait for the db service to be healthy
    # command: flask run --host=0.0.0.0 --port=5001 # run the flask app
    env_file:
      - .env.test                   # load environment variables from the .env file
    networks:                       #
      - app_network_test                 
    restart: unless-stopped         # containers restart automatically if they fail unless it is stopped

  db_test:
    image: postgres:13
    container_name: postgres_db_test
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_test:/var/lib/postgresql/data    # persist data even after the container is stopped
    ports:
      - "5432:5432"         # expose the port to the host machine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"] # check if the db is ready
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network_test         # connect the db to the app network
    restart: unless-stopped # containers restart automatically if they fail unless it is stopped

volumes:
  postgres_data_test:

networks:
  app_network_test:
